### PR TITLE
Fix bag of holding to be just one in the store.

### PR DESCRIPTION
**Pull request by abalabokhin**
If you can buy many bags of holding, items in them are duplicated that is a mess. Moreover, being able to buy many bags of holdings is not a good idea.

### CODE REVIEW

**Comment by Roberciiik** [comment]
This could also be migrated to BGT and EET branches.

**Comment by 11jo** [comment]
Hello @abalabokhin,

I already added the file from p_zombie to the [EE / BGT branch](https://github.com/11jo/DarkHorizons/commit/007a7075dc97865b9acc4be8e8ed17e1457b20c1) (but forgot to mention it in the commit)

I attach the file currently used below if you want to verify they are the same.


Hello @Roberciiik,

In the same commit that adds the correction for CMMERC06.STO, I try to adapt the old setup.tra for bgt, but I am very unsure about it... I don't think the descriptions will be entirely accurate.

I plan to modify the tp2 with the one attached below.... but still... I don't think the descriptions wil be entirely accurate.

Unfortunately, I don't have time to do a thorough review of all items.

[STO.and.Setup.zip](https://github.com/11jo/DarkHorizons/files/11175117/STO.and.Setup.zip)

**Comment by abalabokhin** [comment]
@11jo, thank you. I will close the pull request then.

**Comment by Roberciiik** [comment]
@11jo Thank you for supporting the other branches too. From a short review, it seems that the encoding is wrong for setup-ee.tra files. I will look into it when I found some time and propose pull request or similar.

**Pull request closed without merging**
